### ISSUE TITLE
regression in wsk cli tests correlated to client-go commit 67f06bc

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk-client-go#118]
As shown by comparing the TravisCI results of wsk-cli PRs https://github.com/apache/incubator-openwhisk-cli/pull/422 and https://github.com/apache/incubator-openwhisk-cli/pull/423, The client-go PR #116 (git hash 67f06bc)  introduced failures in the WskCliConsoleTests (see https://travis-ci.org/apache/incubator-openwhisk-cli/builds/505208192#L5182).

@larandersson @rabbah - Please take a look and decide if we need to update test cases, need a compensating fix in the cli, or if the client-go commit was buggy.   This is blocking progress on the next Apache release of the wsk cli and dependent projects.

**Comment by larandersson** [comment]
@dgrove-oss @rabbah From what I can tell, the failing test basically invokes an action, then polls for activations using *wsk activation poll* and verifies that it gets exactly one activation, but for some reason it gets 2. Looking at the changes I introduced, its hard to see how the two methods I modified could have anything to do with that, since all they do is return a header and a string representation of the activation when invoking *wsk activation list*. The API itself has not been changed, so its hard for me to explain what is going on here. But I also noticed that the second test in the same class fails as well, and for that there is an issue #4328. Could they be related?

**Comment by dubee** [comment]
Can we prove this out with a unit test in client-go?

**Comment by larandersson** [comment]
@dubee Don't think so. The test needs to be run against a working OpenWhisk environment. That's probably why it's in the main repo instead of the cli one. Anyway, I forked my cli repo to be in sync with upstream master, updated build.gradle to point to my commit in client-go, built the CLI, then updated my controller and invoker to the latest image and run the failing test manually in CLI (create action, poll for activations, invoke action), and it works just fine! I've also gone over the code and I'm pretty confident that the code I changed never is called from the failing test.

**Comment by rabbah** [comment]
I have reproduced the failure locally. The answer is the following:

```

```

**Comment by rabbah** [comment]
this is the result of activation list as it appears now for me built with the hashes from https://github.com/apache/incubator-openwhisk-cli/pull/423

<img width="1338" alt="Screen Shot 2019-03-14 at 2 42 42 PM" src="https://user-images.githubusercontent.com/4959922/54382982-7630db80-4667-11e9-8092-9a789978f907.png">

**Comment by dubee** [comment]
> @dubee Don't think so. The test needs to be run against a working OpenWhisk environment. That's probably why it's in the main repo instead of the cli one. Anyway, I made sure my cli repo was in sync with upstream master, updated build.gradle to point to my commit in client-go, built the CLI, then updated my controller and invoker to the latest image and run the failing test manually in CLI (create action, poll for activations, invoke action), and it works just fine! I've also gone over the code and I'm pretty confident that the code I changed never is called from the failing test.

We can provide mock backend activation responses to the client-go test, however.

**Comment by rabbah** [comment]
PR opened to address the format change. I think mocking would not have been caught it.

**Comment by dgrove-oss** [comment]
We're tracked down and fixed this
