### ISSUE TITLE
Not adding "api" to the URL 

### ISSUE THREAD

**Issue by tleyden** [apache/incubator-openwhisk-client-go#25]
I'm running against Bluemix, and trying to list activations with:

```
	config, err := WhiskConfigFromEnvironment()
	if err != nil {
		return nil, err
	}
	client, _ := whisk.NewClient(http.DefaultClient, config)
	activations, resp, err := client.Activations.List(nil)
```

In `WhiskConfigFromEnvironment()` I’m setting `config.AUTH` and `config.APIHOST` based on what’s in my `~/.wskprops` file.

However it's getting a 404 because it's trying to go to `http://openwhisk.ng.bluemix.net/v1/namespaces/_/activations`, which is missing `api` in the base url.  

If I run `wsk -d activation list` I can see that it goes to `https://openwhisk.ng.bluemix.net/api/v1/namespaces/_/activations?limit=30&skip=0`.

I verified that it fixes the issue w/ this (hacky) workaround:

```
    requestUrlString := strings.Replace(requestUrl.String(), "v1", "api/v1", 1)

    req, err := http.NewRequest(method, requestUrlString, buf)
```     

After that change, `client.Activations.List(nil)` returns the list of activations.

**Comment by tleyden** [comment]
Another workaround that works is to add the `api` to the url before setting the `config.BaseURL` variable.

If that's the recommend way to use the API, then the docs on the `config.BaseURL` should probably be updated to reflect that.  Currently it's a bit confusing since it says:

```
type Config struct {
    BaseURL   	*url.URL // NOTE :: Default is "openwhisk.ng.bluemix.net"
    ..
}
```

(which would mean that the default val is broken)

**Comment by houshengbo** [comment]
@tleyden I plan to remove openwhisk.ng.bluemix.net as the default URL. Instead, credentials are now able to load in .wskprops, and then whisk.properties if there is a local deployment of openwhisk.

BaseURL will deprecate, since we only need to configure apiHost. BaseURL can be generated from apiHost. If a user creates the *config, they can proceed without hassle by at least setting namespace, auth and apihost for whisk.NewClient.

BTW, the following methods have already been supported to get the config:
```
func GetDefaultConfig() (*Config, error)   // from .wskprops, if not, whisk.properties

func GetWhiskPropertiesConfig() (*Config, error)  //from whisk.properties

func GetWskpropsConfig(path string) (*Config, error)  // from .wskprops
```
please check https://github.com/apache/incubator-openwhisk-client-go/blob/master/whisk/wskprops.go.

**Comment by houshengbo** [comment]
@tleyden I have fixed this issue. Feel free to reopen it if it still valid.

**Comment by tleyden** [comment]
Cool, I'll pull the latest code and retest this

**Comment by tleyden** [comment]
> Instead, credentials are now able to load in .wskprops

Does it use that environment variable to find out which `.wskprops` to load?  That would be useful when juggling several `.wskprops` files (staging, production, etc)
